name: Build and deploy Loja Virtual
on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    name: Build and deploy loja virtual spring app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml