name: Build and deploy Ecommerce Loja Virtual
on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    name: Build and deploy loja virtual spring app
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Postgres1756
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --name myapp_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create role
        run: docker exec myapp_db bash -c "POSTGRES_PASSWORD=Postgres1756 psql -U postgres -c \"create role myapp with createdb login password 'myapp'\""

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml