name: Build and deploy Ecommerce Loja Virtual
on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    name: Build and deploy loja virtual spring app
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Postgres1756
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml